FROM node:20-alpine

WORKDIR /app


COPY package.json package-lock.json* ./


RUN npm ci


COPY . .


EXPOSE 4200


ENV NODE_ENV=development


CMD ["npm", "run", "start", "--", "--host", "0.0.0.0", "--port", "4200"]